### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by golddotasksquestions** [LikeLakers2/beeboat#1]
I'm not sure how else to contact you, I could not find you on Discord or reddit and you don't seem to have any public contacts here either.
Just want to let you know that I really enjoyed and appreciated your input and exchange over different input buffer approaches and that it made me look at input buffers in different ways. I hope you did not feel like I was ignoring your ideas. That was not at all the case. They made me think and reconsider a lot.

**Comment by LikeLakers2** [comment]
Responded on Discord, my username is `MichiRecRoom#9507`.

tl;dr if you need it: don't worry, I don't really feel like you were ignoring me. even if I did feel that way, there's a lot more to how I was feeling, a lot that didn't involve you, that ended up invoking my last comment on that thread.
